### ISSUE TITLE
[Bug] Not detecting act installed as GH CLI extension

### ISSUE THREAD

**Issue by FelixNgFender** [SanjulaGanepola/github-local-actions#73]
As titled, even on refresh it still says act not installed and actions cannot be run because of that. Reinstall through the dropdown GUI tells me that act extension is already installed. Manually invoking `gh act` works though.

```shell
 *  Executing task: set -o pipefail; act --workflows ".github/workflows/publish-docs.yml" --secret-file "" --var-file "" --input-file "" --eventpath "" 2>&1 | tee "/home/felixngfender/.config/Code/User/globalStorage/sanjulaganepola.github-local-actions/Publish docs #2 - 20241124_213619.log" 

/usr/bin/bash: line 1: act: command not found

 *  The terminal process "/usr/bin/bash '-c', 'set -o pipefail; act --workflows ".github/workflows/publish-docs.yml" --secret-file "" --var-file "" --input-file "" --eventpath "" 2>&1 | tee "/home/felixngfender/.config/Code/User/globalStorage/sanjulaganepola.github-local-actions/Publish docs #2 - 20241124_213619.log"'" failed to launch (exit code: 127). 
```

**Comment by SanjulaGanepola** [comment]
Hello @FelixNgFender. Thank you for sharing this issue. Looks like I missed a couple steps for the GH CLI installation method. I have gone ahead and pushed a new version you can install (`v1.1.1`).

In the update (#73), I added a new configuration to be able to set the base `act` command. In the case of GH CLI, it will need to be `gh act`. From the `Components` view, you can go ahead and select the option to install with `GitHub CLI` again and this will update the setting correctly. Please let me know if this resolved the issue.

![image](https://github.com/user-attachments/assets/2354893c-9529-42fd-a055-94e0481d9439)

**Comment by FelixNgFender** [comment]
Awesome! It's working now and thanks for the prompt reply.
