### ISSUE TITLE
Docker installation not recognized

### ISSUE THREAD

**Issue by ErikKalkoken** [SanjulaGanepola/github-local-actions#77]
Thank you for sharing this great app.

I have docker CE installed on my system, but the extension says it is missing. Would appreciate any pointers on how I could troubleshoot this.

My system:
- Ubuntu 22.04 LTS
- VSCode 1.95.3
- Github Location Action: 1.1.1
- Docker CE: 27.3.1
 
Screenshot from VS Code:

![Screenshot from 2024-11-25 16-09-22](https://github.com/user-attachments/assets/ac351012-6d33-4f41-aae3-77346345da3a)

**Comment by SanjulaGanepola** [comment]
Hello @ErikKalkoken. Thank you for sharing this issue. There indeed was a bug with detecting the Docker Engine component status and I have a PR (https://github.com/SanjulaGanepola/github-local-actions/pull/70) that I will be merging soon to address this. I will let you know when I have created a release.

In the meantime, you can still use the extension as normal as long as you have manually verified that Docker Engine is running.

**Comment by ErikKalkoken** [comment]
tyvm for your quick and helpful reply. I must confess I did not even try it, but will do so now.

**Comment by SanjulaGanepola** [comment]
@ErikKalkoken I just published a `1.1.2` release that contains the fix. Please let me know if you encounter the issue still.

**Comment by ErikKalkoken** [comment]
Ty for the fix. I have installed the latest version and now getting the error "invalid permissions".

All my docker interactions on the command line require sudo, maybe this is the issue here too?

Do you want me to open a new issue or will you re-open this one?

See screenshot attached.  
![Screenshot from 2024-11-28 17-29-38](https://github.com/user-attachments/assets/8beafd10-7860-4b7b-88b2-13ce7844c7b0)

**Comment by SanjulaGanepola** [comment]
@ErikKalkoken This is to be expected as you are trying to manage docker as a non-root user. In my latest fix, I also added a button to help resolve this permission issue. If you hover over that tree item, you should see a lock button to `Fix Permission`. This will create a Unix group called `docker` and add your non-root user to it. Once you do that, you may need to restart your PC for the changes to take affect. Can you have a try with that and let me know if that resolves the issue?

For Linux, this is a essentially a post installation step that is required for Docker Engine: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by ErikKalkoken** [comment]
tyvm that worked.
