### ISSUE TITLE
Proposal Move Gif to wiki pseudo repo

### ISSUE THREAD

**Issue by ChristopherHX** [SanjulaGanepola/github-local-actions#84]
In your readme use a link like `![demo](https://raw.githubusercontent.com/wiki/SanjulaGanepola/github-local-actions/demo.gif)`

And push this `demo.gif` file to the root of `https://github.com/SanjulaGanepola/github-local-actions.wiki` a shadow repo.

This wiki link works without enabling the GitHub wiki.

In my vscode extension the repo size growth were going into the wrong direction when updating the demos.

Your vsix file would shrink to ca. 50% or more by excluding it from beeing packaged, without moving it to the wiki.

_Feel free to close this if you want to keep further versions of your gif with the source code_

**Comment by SanjulaGanepola** [comment]
> I'm not long at linkedin at all and my profile is still something to work on, sent you an invite.

> Some of my actions projects are planned to move to https://github.com/actions-oss with multiple org owners. While nektos has only Casey as owner.

> Including a wip guide going beyond just act: https://actions-oss.github.io/

Thanks for the connect request! We can discuss further over LinkedIn and I'm interested to hear what you are planning to include in this guide.

> Your vsix file would shrink to ca. 50% or more by excluding it from beeing packaged, without moving it to the wiki.

Removing this from the VSIX is an awesome suggestion. I have opened https://github.com/SanjulaGanepola/github-local-actions/pull/86 to remove everything under images from being bundled. I am considering creating a documentation page or opening the Wiki, but have not yet decided. Until then, I will keep the images in their current location for now as I can still reference them with links like you suggested.
